### PR TITLE
Insert scope variables to compileDirective.

### PR DESCRIPTION
**Pull request by elvinyung**
Alright. PR part 1.

I added a parameter `scope` to `compileDirective` that lets you insert things into the scope. This makes it easy to test a ton of directive functionality.

### CODE REVIEW

**Comment by elvinyung** [comment]
The build is failing right now because of coverage, but that's because (I think) the standard branch for `compileDirective` isn't being tested.

Wat do?

**Comment by RickEyre** [comment]
Hmm, yeah. It's something to do with code coverage. To investigate you can open the `index.html` generated by the code coverage tool. That should be under `Coverage` folder or something like that.

Also, could you update the documentation branch once this is merged and also write an example of it being used. We use jsdocs, so putting it in the example alongside the code should generate it for you.

**Comment by scottybarr** [comment]
Yep, error is `else path not taken` when we have branch threshold set to 100% for the scope less `compileDirective` function.

Can probably change the skipped unit test on Line 227 to something like:
```
it('should compile directive correctly', function() {
  var element = EasyTest.compileDirective('<div test-directive><b>Unit test</b></div>');
  expect(element.html()).to.equal('<b>Unit test</b>');
});
```

**Comment by elvinyung** [comment]
Yep, ended up writing an actual(ish) unit test for it.

@RickEyre ptal!

**Comment by RickEyre** [comment]
@elvinyung can you squash your fix for the unit test into the broken commit? After that it looks good!

**Comment by elvinyung** [comment]
@RickEyre I did the things, but you'll have to `npm publish` them from your end because I don't have the credentials.

Fine if I merge?

**Comment by RickEyre** [comment]
yup sounds good, i'll take care of the publish

**Comment by RickEyre** [comment]
@elvinyung published.

**Pull request merged**
